### ISSUE TITLE
"An error has occurred: SQL Error line 1:42: unexpected end of file" in JSON export from Betools 

### ISSUE THREAD

**Issue by mpomeran** [iandol/bookends-tools#11]
Thanks so much for this wonderful set of tools! 
I use this along with your scrivomatic/pandocomatic workflow. 
It's fantastic! 

I'm running into some trouble with the exporting of the BibTex file to JSON. It works with the smaller groups in 
my library like a charm. But when I try to export the larger 1500+ references to a large JSON file, I get the following error:
"An error has occurred: SQL Error line 1:42: unexpected end of file"
I wrote to Jon at Sonny who said to contact you. I rebuilt the library, so it's not this. 
And I'm trying to go through the bib entries to see if there is something malformed. 

Do you have any thoughts as to what I might try? It might make sense to export a BibTex file and see if that is properly formatted. But I'm hoping that you have another suggestion before I start my weeding. 

Maurice

**Comment by iandol** [comment]
@mpomeran — are you sure all your cite keys are not empty? That normally can cause the JSON conversion to fail. You can check this easily by making a smart group (SQL) that finds these automatically:

![Screenshot 2020-09-21 at 15 44 15_SMALL](https://user-images.githubusercontent.com/153905/93742878-7a0cc900-fc21-11ea-9bde-3564615c7be1.png)

Or check the BibTeX file searching for 

The most recent version of the alfred workflow (V1.3.4) should have better behaviour in this case...
