### ISSUE TITLE
Open PDF?

### ISSUE THREAD

**Issue by hposen** [iandol/bookends-tools#14]
Hi. Is it possible to open the PDF associated with a reference? I know I can use shift with becite to see a preview, but I would like to be able to open the pdf directly. Perhaps a bepdf, which searches the library and for the selected reference in the menu displays the pdf in the default viewer? Thanks much. Bookends-Tools is super!

**Comment by iandol** [comment]
I'm currently all out of modifier keys which would be the easy solution. I can possibly add a new action but I don't have much time at the moment...

**Comment by iandol** [comment]
<img width="676" alt="Screen Shot 2021-07-13 at 10 34 48" src="https://user-images.githubusercontent.com/153905/125381479-8dfb0480-e3c6-11eb-8a21-c885400600b4.png">

You can open the PDF from the quick look window, which requires a single click.

**Comment by iandol** [comment]
I found a quick fix for this released in V1.3.7, you can now use  [command][option] to open an attached PDF directly...
