### ISSUE TITLE
Two issues with toBibTeX script

### ISSUE THREAD

**Issue by mk-uc** [iandol/bookends-tools#15]
The first is more of a request, the second is an issue I'm running into:

1. do you know if it's possible to run this script with Launchbar? It seems that the script takes arguments (path and group), and I'm not sure how to insert those into Launchbar. If I wanted to encode those variables into the script itself, what would I change?
2. I normally have the default format set to Chicago, though the insert citation format is set to pandoc. However, if I export it that way I just get a bunch of cite keys. If I change the default format to BibTeX, it does correctly export the BibTeX format, however, there are no line breaks either within a reference or between them so that it just looks like one big file with never ending text. Is there a setting I might have wrong here?

Thanks!

**Comment by iandol** [comment]
1. I've never used Launchbar, though each of the scripts can certainly be used by Launchbar (they are a combination of bash, rubt and applescript); **however** this collection makes heavy use of Alfred's amazing Workflow editor tools. It runs scripts, but also manages flows of queries from script to script and this certainly will not easily convert to Launchbar which I assume uses a very different system. I don't know how you "chain" things together in Launchbar... The search citation tools like `becite` also require a GUI to output the list of citations for seelction, and I don't know if Launchbar can generate an interactive UI for such items?
2. Which tool are you referring to? `becite` is designed to insert temporary citations whereas `bebib` inserts formatted references. You can get a formatted ref using [control] in `becite`. These are mostly used with single refs. Exporting BibTeX is handled by `betobibtex`, though personally I now prefer to use Bookends directly as with a large database the Applescript is much much slower and uses more memory.

**Comment by iandol** [comment]
@mk-uc -- Hm, I should have read the title, you are specifically referring to toBibTeX 🤣 — ok I still can't answer (1) though I'm sure it can handle this easily. For (2) I don't quite understand the problem or at least can't reproduce. I have my `citationStyle` variable set to `APA 7th Edition` and my `tempCitationStyle` set to `Pandoc`, but toBibTeX always outputs BibTeX without issue for me?
