### ISSUE TITLE
Editors in edited books are appearing "unknown"

### ISSUE THREAD

**Issue by DesBw** [iandol/bookends-tools#4]
[a screenshot](http://take.ms/TJOtL)

is it possible to add  Editors as option to the  authors?

**Comment by iandol** [comment]
Yes, this is on my to-do list already :-) — it will be easy to add, just need some time to do it!

**Comment by Dellu** [comment]
that will be nice: thanks

**Comment by iandol** [comment]
Please see https://github.com/iandol/bookends-tools/issues/3#issuecomment-408582852
