### ISSUE TITLE
BibTeX export

### ISSUE THREAD

**Issue by mclearc** [iandol/bookends-tools#6]
Sometimes when I use betobib export the exported bibfile does not contain valid bibtex but rather simply the list of entries in the form of their PDF title (e.g. citekey_title-with-no-spaces). This will be true even if I have the default format set to Bibtex. Do you have any idea why this would be?

Thanks again for these great tools.

**Comment by iandol** [comment]
Hi, sorry for the late reply. I'm not quite sure what is going on there, do you have a small database where you can reproduce the problem and I can then take a look...

**Comment by mclearc** [comment]
Unfortunately this isn't a reliably reproducible bug as far as I can see. It happens intermittently. But the next time it happens I'll try with a small library and see if I can reproduce it.
