### ISSUE TITLE
Quickadd not working when evernote is open

### ISSUE THREAD

**Issue by chaxu443** [iandol/bookends-tools#7]
Thanks very much for this very useful tool! I recently found that if my evernote is open, I cannot use the quickadd function to import DOI directly to Bookends. The DOI is still copied to the clipboard but left in the evernote instead of being sent to Bookends. Please could you look into this issue? Much appreciated!

**Comment by iandol** [comment]
Hi sorry for such a late reply. Quickadd uses applescript to activate bookends so unless it isn't running I can see how this could occur?

**Comment by bcdavasconcelos** [comment]
About quick add, it could be replaced with this little script that does not rely on GUI scripting:

```
on run
tell application "Bookends"
	set pubListitem to the clipboard
	set pubList to quick add {pubListitem}
end tell
end run

```

**Comment by iandol** [comment]
> About quick add, it could be replaced with this little script that does not rely on GUI scripting:
> 
> ```
> on run
> tell application "Bookends"
> 	set pubListitem to the clipboard
> 	set pubList to quick add {pubListitem}
> end tell
> end run
> ```

@bcdavasconcelos — when I tested the new Applescript interface for quick-add, I found it kept Bookends in the foreground until the references was either found or not. This is different behaviour that the UI, where the search happens in the background. Forcing Bookends to stay in the foreground until the search completes really disrupts the flow. I could make a wishlist item on the bookends forum to see if they can change the behaviour, as I do think getting away from UI scripting is preferable wherever possible...

**Comment by iandol** [comment]
@bcdavasconcelos -- you can uncomment line 18 and 19 (and comment the UI scripting bit) and test if you see this behaviour: https://github.com/iandol/bookends-tools/blob/master/source/quickAdd.js#L18 — I still see it with BE 13.4.4...

**Comment by bcdavasconcelos** [comment]
Hi Ian, 
I have a separate workflow with some other BE tools and I frequently copy the DOI or ISBN from PDFs I am reading in DEVONthink and use Alfred to call this little quick add script. I never had BE come to the foreground while the search was being performed. The only thing that happens is a very discreate notification saying if a reference was found or not.
Perhaps you could test it without the rest of the javascript part and see if this happens.

**Comment by iandol** [comment]
@bcdavasconcelos — Ah yes, it could very well be my error, I'll give the minimalist code a test!

**Comment by iandol** [comment]
Yes, indeed it was my error, I don't need to "activate" the app for that command to work. I've simplfied the javascript version and will release a new bookends-tools in a few days time, thanks for the feedback!

**Comment by iandol** [comment]
V1.3.4 has fixed this...
