### ISSUE TITLE
Add translator and editor to JSON string coming from findReferencesAll.rb 

### ISSUE THREAD

**Issue by bcdavasconcelos** [iandol/bookends-tools#9]
Hi Ian,
there is something I been meaning to ask. 

The `findReferencesAll.rb` script returns `authors` and `date` as the title of the json string and `title of the work` as the subtitle. Could you point me out in the right direction so that I could add editor and/or translator as well? I gave it a try, but I am ruby illiterate. 

Thanks!

**Comment by iandol** [comment]
The main function that gets the info from Bookends is here:

https://github.com/iandol/bookends-tools/blob/master/source/findReferencesAll.rb#L84

This returns JSON which is easily parsed in the loop starting line 94, so for the editor (which is there I see), `@editors[i] = parseAuthors(thisrec['editors'])` — for editors they are shown if author is blank by default. To change the display the function is this one:

https://github.com/iandol/bookends-tools/blob/master/source/findReferencesAll.rb#L159

By the way, Visual Studio Code has a really nice debugger for Ruby and this github repo has a config (.vscode/launch.json) so you can step debug findReferences scripts, the config passes variables in so the script gets exactly what it would get from Alfred. That should make it easier to understand what is going on in that script. Good luck!

**Comment by bcdavasconcelos** [comment]
Thanks, Ian! After a couple of hours of trial and error, I finally manage to get it working. 
The speed with which this ruby script works from Alfred is pretty amazing.

**Comment by iandol** [comment]
> Thanks, Ian! After a couple of hours of trial and error, I finally manage to get it working.
> The speed with which this ruby script works from Alfred is pretty amazing.

@bcdavasconcelos -- yeah, I was originally worried that Ruby would be too slow for this, but I really dislike Applescript, and my javascript skills are weak, and once optimised Ruby + osascript was more than fast enough...
